"""NumPy backend kernels.

The implementations are shared with the CUDA backend because NumPy and CuPy
provide the same array-operation surface used by tensors.
"""

from ._array import (
    adam_update,
    adam_updates,
    arange,
    arg_extremum,
    binary,
    binary_cross_entropy,
    binary_cross_entropy_gradient,
    cast_tensor,
    clip,
    clip_gradient,
    comparison,
    concat,
    cross_entropy,
    cross_entropy_gradient,
    distributions_valid,
    division_denominator_gradient,
    extremum,
    extremum_gradient,
    eye,
    full,
    linspace,
    logsumexp,
    logsumexp_gradient,
    matmul,
    matmul_gradient,
    negate,
    normalization,
    normalization_gradient,
    one_hot_targets,
    outer,
    outer_gradient,
    power_base_gradient,
    power_exponent_gradient,
    reduction,
    reduction_gradient,
    rmsprop_update,
    rmsprop_updates,
    sgd_update,
    sgd_updates,
    slice_scatter,
    slice_tensor,
    stack,
    sum_products_to_shape,
    sum_to_shape,
    transpose,
    unary,
    unary_gradient,
    where,
    where_gradient,
)

__all__ = [name for name in globals() if not name.startswith("_")]
